name: example
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  story_picker:
    path: ../

  cupertino_icons: ^1.0.8
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  video_thumbnail:
    git:
      url: https://github.com/julek-kal/video_thumbnail
      ref: 734a2d5

flutter:
  uses-material-design: true
