name: story_picker
description: Story Picker.
version: 0.0.7+10
homepage: https://github.com/mstrkn/StoryPicker.git
publish_to: 'none'

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_keyboard_visibility: ^5.4.0
  flutter_image_compress: ^1.1.3
  auto_size_text_field: ^2.1.0
  permission_handler: ^10.2.0
  visibility_detector: ^0.3.3
  just_the_tooltip: ^0.0.12
  page_transition: ^2.0.9
  path_provider: ^2.0.11
  video_trimmer: ^1.2.0
  photo_manager: ^2.5.1+1
  image_cropper: ^3.0.1
  video_player: ^2.4.8
  fluttertoast: ^8.1.1
  file_picker: ^5.2.3
  photo_view: ^0.14.0
  platform: ^3.1.0
  provider: ^6.0.4
  camera: ^0.10.0+4
  chewie: ^1.3.6
  logger: ^1.1.0
  path: ^1.8.3

  photofilters:
    git:
      url: https://github.com/mstrkn/photofilters.git
      ref: develop

  video_thumbnail:
    git:
      url: https://github.com/julek-kal/video_thumbnail
      ref: 734a2d5

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  path: ^1.8.2
  video_thumbnail:
    git:
      url: https://github.com/julek-kal/video_thumbnail
      ref: 734a2d5

flutter:

  uses-material-design: true

  fonts:
    - family: FreightSans
      fonts:
        - asset: assets/fonts/FreightSans-Medium.otf
          weight: 500

    - family: MADECanvas
      fonts:
        - asset: assets/fonts/MADECanvas.otf

    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova.otf

    - family: AvenyT
      fonts:
        - asset: assets/fonts/AvenyT/AvenyT-Regular.otf
          style: normal
          weight: 400
        - asset: assets/fonts/AvenyT/AvenyT-Medium.otf
          weight: 500

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
