name: story_picker
description: Story Picker.
version: 0.0.7+2
homepage: https://github.com/mstrkn/StoryPicker.git
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_keyboard_visibility: ^5.1.0
  flutter_image_compress: ^1.1.0
  auto_size_text_field: ^1.0.1
  permission_handler: ^8.3.0
  visibility_detector: ^0.2.2
  page_transition: ^2.0.4
  video_thumbnail: ^0.4.3
  path_provider: ^2.0.8
  video_trimmer: ^1.0.0
  super_tooltip: ^1.0.1
  photo_manager: ^1.3.10
  image_cropper: ^1.4.1
  video_player: ^2.2.9
  fluttertoast: ^8.0.8
  photo_view: ^0.13.0
  provider: ^6.0.1
  camera: ^0.9.4+5
  chewie: ^1.2.2
  logger: ^1.1.0
  path: ^1.8.1

  photofilters:
    git:
      url: https://github.com/mstrkn/photofilters.git
      ref: develop

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  provider: ^6.0.1
  path: ^1.8.1

flutter:

  uses-material-design: true

  fonts:
    - family: FreightSans
      fonts:
        - asset: assets/fonts/FreightSans-Medium.otf
          weight: 500

    - family: MADECanvas
      fonts:
        - asset: assets/fonts/MADECanvas.otf

    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova.otf

    - family: AvenyT
      fonts:
        - asset: assets/fonts/AvenyT/AvenyT-Regular.otf
          style: normal
          weight: 400
        - asset: assets/fonts/AvenyT/AvenyT-Medium.otf
          weight: 500

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
