name: story_picker
description: Story Picker.
version: 0.0.8+16
homepage: https://github.com/mstrkn/StoryPicker.git
publish_to: 'none'

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_keyboard_visibility: ^6.0.0
  flutter_image_compress: ^2.3.0
  auto_size_text_field: ^2.2.4
  permission_handler: ^11.3.1
  visibility_detector: ^0.4.0+2
  just_the_tooltip: ^0.0.12
  video_thumbnail: ^0.5.3
  page_transition: ^2.1.0
  path_provider: ^2.1.5
  video_trimmer: ^3.0.1
  photo_manager: ^3.2.3
  image_cropper: ^8.0.2
  video_player: ^2.9.2
  fluttertoast: ^8.2.8
  file_picker: ^8.1.4
  photo_view: ^0.15.0
  platform: ^3.1.6
  provider: ^6.1.2
  camera: ^0.11.0
  chewie: ^1.8.5
  logger: ^2.4.0
  path: ^1.9.0

  photofilters:
    git:
      url: https://github.com/noeGnh/photofilters.git
      ref: develop

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: FreightSans
      fonts:
        - asset: assets/fonts/FreightSans-Medium.otf
          weight: 500

    - family: MADECanvas
      fonts:
        - asset: assets/fonts/MADECanvas.otf

    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova.otf

    - family: AvenyT
      fonts:
        - asset: assets/fonts/AvenyT/AvenyT-Regular.otf
          style: normal
          weight: 400
        - asset: assets/fonts/AvenyT/AvenyT-Medium.otf
          weight: 500

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
